apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-template
  namespace: vm-runner-test
spec:
  runStrategy: Manual
  template:
    metadata:
      name: runner
    spec:
      architecture: amd64
      terminationGracePeriodSeconds: 30
      domain:
        firmware:
          kernelBoot:
            container:
              image: container-registry.local:5000/fedora-cloudimage:{{ kernel_version }}
              initrdPath: /boot/initramfs-{{ kernel_version }}.img
              kernelPath: /boot/bzImage-{{ kernel_version }}
              imagePullPolicy: Always
            kernelArgs: console=ttyS0
        devices:
          filesystems:
            - name: runner-info
              virtiofs: {}
          disks:
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
        cpu:
          cores: 4
        resources:
          requests:
            memory: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              users:
                - name: runner
                  homedir: /home/runner
                  sudo: ["ALL=(ALL) NOPASSWD:ALL"]
              mounts:
                - [ runner-info, /runner-info/, virtiofs, "rw,relatime,user=fedora" ]
              packages:
                - jq
              bootcmd:
                - "sudo mkdir /opt/runner"
                - "curl -sL https://github.com/actions/runner/releases/download/v2.322.0/actions-runner-linux-x64-2.322.0.tar.gz | sudo tar -xz -C /opt/runner"
                - "sudo /opt/runner/bin/installdependencies.sh"
              runcmd:
                - "sudo chown -R runner: /opt/runner"
                - "sudo runuser -l runner -c '/opt/runner/run.sh --jitconfig $(jq -r '.jitconfig' /runner-info/runner-info.json)'"
                - "sudo poweroff"
